version: '3'

services:
  livekit:
    image: livekit/livekit-server:v1.4.5
    command: --config ./livekit.yaml --node-ip 127.0.0.1
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    cap_add:
      - CAP_SYS_ADMIN
    volumes:
      - ./livekit.yaml:/livekit.yaml
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - redis
    links:
      - redis
  egress:
    image: livekit/egress:latest
    environment:
      - EGRESS_CONFIG_FILE=/egress.yaml
    volumes:
      - ./test/egress.yaml:/egress.yaml
      - ./test/out:/out
      - ./test/recording:/recording
    restart: unless-stopped
    depends_on:
      - livekit
      - redis
    links:
      - livekit
      - redis
    cap_add:
      - CAP_SYS_ADMIN
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
